version: '3.9'
services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:mongo@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
