name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to OCI
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_SECRET }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.SSH_PATH }}
          git pull origin main
          make down
          make build
          echo "Deleting old Docker images..."
          docker image prune -a -f
